# Generated by Django 2.2.4 on 2021-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_professor'),
        ('students', '0002_auto_20210620_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='classes.Class'),
        ),
    ]
