# Generated by Django 2.2.4 on 2021-06-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.Professor'),
        ),
    ]
