# Generated by Django 2.2.4 on 2021-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='avatar',
            field=models.CharField(default='https://picsum.photos/200/300', max_length=255),
        ),
        migrations.AddField(
            model_name='professor',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
